### ISSUE TITLE
Error running docker-compose build

### ISSUE THREAD

**Issue by CarbonMan** [maccam912/ppp#2]
I am not sure what I am doing wrong but when I run ;
docker-compose build

I get this;
The compose file './docker-compose.yml' is invalid because: Unsupported config option for services: 'server'

Thanks.

**Comment by nstankov-bg** [comment]
Hey, try this as your docker-compose.yml file

```yaml
version: "3.6"
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
  client:
    build: ./client
    ports:
      - "8009:8009"
```
